// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZAD_REK.Models;

#nullable disable

namespace ZAD_REK.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20230419150842_Pierwsza_tabela+Dane")]
    partial class Pierwsza_tabelaDane
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ZAD_REK.Models.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"), 1L, 1);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EditedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("IdProduct");

                    b.ToTable("Products", (string)null);

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            CreatedAt = new DateTime(2023, 4, 19, 17, 8, 42, 55, DateTimeKind.Local).AddTicks(2503),
                            EditedAt = new DateTime(2023, 4, 19, 17, 8, 42, 55, DateTimeKind.Local).AddTicks(2527),
                            Price = 1111.0,
                            ProductDesc = "Desc1",
                            ProductName = "Prod1"
                        },
                        new
                        {
                            IdProduct = 2,
                            CreatedAt = new DateTime(2023, 4, 19, 17, 8, 42, 55, DateTimeKind.Local).AddTicks(2532),
                            EditedAt = new DateTime(2023, 4, 19, 17, 8, 42, 55, DateTimeKind.Local).AddTicks(2533),
                            Price = 2222.0,
                            ProductName = "Prod2"
                        },
                        new
                        {
                            IdProduct = 3,
                            CreatedAt = new DateTime(2023, 4, 19, 17, 8, 42, 55, DateTimeKind.Local).AddTicks(2535),
                            EditedAt = new DateTime(2023, 4, 19, 17, 8, 42, 55, DateTimeKind.Local).AddTicks(2537),
                            Price = 3333.0,
                            ProductDesc = "Desc3",
                            ProductName = "Prod3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
